<?php

return [
    'header' => [
        'TIPO_INSTRUMENTO',
        'NUMERO_INSTRUMENTO',
        'ANO_INSTRUMENTO',
        'CPF',
        'SEXO',
        'CNPJ',
        'FLAG_CAD_ESTADUAL',
        'SISTEMA_CAD_ESTADUAL',
        'IDENTIFICADOR_CAD_ESTADUAL',
        'FLAG_CAD_MUNICIPAL',
        'SISTEMA_CAD_MUNICIPAL',
        'IDENTIFICADOR_CAD_MUNICIPAL',
        'FLAG_CAD_DISTRITAL',
        'SISTEMA_CAD_DISTRITAL',
        'IDENTIFICADOR_CAD_DISTRITAL',
        'FLAG_CAD_NA_PONTOS_PONTOES',
        'FLAG_CAD_ES_PONTOS_PONTOES',
        'SISTEMA_CAD_ES_PONTOS_PONTOES',
        'IDENTIFICADOR_CAD_ES_PONTOS_PONTOES',
        'FLAG_CAD_SNIIC',
        'SISTEMA_CAD_SNIIC',
        'IDENTIFICADOR_CAD_SNIIC',
        'FLAG_CAD_SALIC',
        'FLAG_CAD_SICAB',
        'FLAG_CAD_OUTROS',
        'SISTEMA_CAD_OUTROS',
        'IDENTIFICADOR_CAD_OUTROS',
        'FLAG_ATUACAO_ARTES_CENICAS',
        'FLAG_ATUACAO_AUDIOVISUAL',
        'FLAG_ATUACAO_MUSICA',
        'FLAG_ATUACAO_ARTES_VISUAIS',
        'FLAG_ATUACAO_PATRIMONIO_CULTURAL',
        'FLAG_ATUACAO_MUSEUS_MEMORIA',
        'FLAG_ATUACAO_HUMANIDADES'
    ],
    "parameters_csv_default" => [
        "status" => '1'
    ],
    'opportunities' => [
        '4788' => [
            'TIPO_PROPONENTE' => 'field_1098',
            'TIPO_INSTRUMENTO' => '',
            'NUMERO_INSTRUMENTO' => '',
            'ANO_INSTRUMENTO' => '',
            'CPF' => 'field_1104',
            'SEXO' => 'csvMap',
            'CNPJ' => 'field_1118',
            'FLAG_CAD_ESTADUAL' => 0,            
            'FLAG_CAD_MUNICIPAL' => 1,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,           
            'FLAG_ATUACAO_ARTES_CENICAS' => 0,
            'FLAG_ATUACAO_AUDIOVISUAL' => 0,
            'FLAG_ATUACAO_MUSICA' => 0,
            'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
            'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
            'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
            'FLAG_ATUACAO_HUMANIDADES' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo',
            'DIR_CSV' => __DIR__.'/csv/deParaSexo.csv',
        ],
        '4789' => [
                'TIPO_PROPONENTE' => null,
                'TIPO_INSTRUMENTO' => '',
                'NUMERO_INSTRUMENTO' => '',
                'ANO_INSTRUMENTO' => '',
                'CPF' => 'field_1126',
                'SEXO' => 'field_1145',
                'CNPJ' => '',
                'FLAG_CAD_ESTADUAL' => 0,            
                'FLAG_CAD_MUNICIPAL' => 1,            
                'FLAG_CAD_DISTRITAL' => 0,            
                'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
                'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
                'FLAG_CAD_SNIIC' => 0,            
                'FLAG_CAD_SALIC' => 0,
                'FLAG_CAD_SICAB' => 0,
                'FLAG_CAD_OUTROS' => 0,           
                'FLAG_ATUACAO_ARTES_CENICAS' => 0,
                'FLAG_ATUACAO_AUDIOVISUAL' => 0,
                'FLAG_ATUACAO_MUSICA' => 0,
                'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
                'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
                'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
                'FLAG_ATUACAO_HUMANIDADES' => 0,
                'PESSOA_FISICA' => 'Pessoa Física',
                'PESSOA_JURIDICA' => 'Pessoa Jurídica',
                'COLETIVO' => 'Coletivo',   
                           
        ],
        '4790' => [
            'TIPO_PROPONENTE' => null,
            'TIPO_INSTRUMENTO' => '',
            'NUMERO_INSTRUMENTO' => '',
            'ANO_INSTRUMENTO' => '',
            'CPF' => 'field_1169',
            'SEXO' => 'field_1158',
            'CNPJ' => '',
            'FLAG_CAD_ESTADUAL' => 0,            
            'FLAG_CAD_MUNICIPAL' => 1,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,           
            'FLAG_ATUACAO_ARTES_CENICAS' => 0,
            'FLAG_ATUACAO_AUDIOVISUAL' => 0,
            'FLAG_ATUACAO_MUSICA' => 0,
            'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
            'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
            'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
            'FLAG_ATUACAO_HUMANIDADES' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo',   
        ],
        '4791' => [
            'TIPO_PROPONENTE' => 'field_1302',
            'TIPO_INSTRUMENTO' => '',
            'NUMERO_INSTRUMENTO' => '',
            'ANO_INSTRUMENTO' => '',
            'CPF' => 'field_1188',
            'SEXO' => 'field_1186',
            'CNPJ' => 'field_1310',
            'FLAG_CAD_ESTADUAL' => 0,            
            'FLAG_CAD_MUNICIPAL' => 1,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,           
            'FLAG_ATUACAO_ARTES_CENICAS' => 0,
            'FLAG_ATUACAO_AUDIOVISUAL' => 0,
            'FLAG_ATUACAO_MUSICA' => 0,
            'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
            'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
            'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
            'FLAG_ATUACAO_HUMANIDADES' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo', 
        ],
        '4792' => [
            'TIPO_PROPONENTE' => null,
            'TIPO_INSTRUMENTO' => '',
            'NUMERO_INSTRUMENTO' => '',
            'ANO_INSTRUMENTO' => '',
            'CPF' => 'field_1199',
            'SEXO' => 'field_1197',
            'CNPJ' => '',
            'FLAG_CAD_ESTADUAL' => 0,            
            'FLAG_CAD_MUNICIPAL' => 1,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,           
            'FLAG_ATUACAO_ARTES_CENICAS' => 0,
            'FLAG_ATUACAO_AUDIOVISUAL' => 0,
            'FLAG_ATUACAO_MUSICA' => 0,
            'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
            'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
            'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
            'FLAG_ATUACAO_HUMANIDADES' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo', 
        ],
        '4793' => [
            'TIPO_PROPONENTE' => 'field_1215',
            'TIPO_INSTRUMENTO' => '',
            'NUMERO_INSTRUMENTO' => '',
            'ANO_INSTRUMENTO' => '',
            'CPF' => 'field_1238',
            'SEXO' => 'field_1225',
            'CNPJ' => '',
            'FLAG_CAD_ESTADUAL' => 0,            
            'FLAG_CAD_MUNICIPAL' => 1,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,           
            'FLAG_ATUACAO_ARTES_CENICAS' => 0,
            'FLAG_ATUACAO_AUDIOVISUAL' => 0,
            'FLAG_ATUACAO_MUSICA' => 0,
            'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
            'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
            'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
            'FLAG_ATUACAO_HUMANIDADES' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo', 
        ],
        '4794' => [
            'TIPO_PROPONENTE' => null,
            'TIPO_INSTRUMENTO' => '',
            'NUMERO_INSTRUMENTO' => '',
            'ANO_INSTRUMENTO' => '',
            'CPF' => 'field_1251',
            'SEXO' => 'field_1253',
            'CNPJ' => 'field_1242',
            'FLAG_CAD_ESTADUAL' => 0,            
            'FLAG_CAD_MUNICIPAL' => 1,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,           
            'FLAG_ATUACAO_ARTES_CENICAS' => 0,
            'FLAG_ATUACAO_AUDIOVISUAL' => 0,
            'FLAG_ATUACAO_MUSICA' => 0,
            'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
            'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
            'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
            'FLAG_ATUACAO_HUMANIDADES' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo', 
        ],
        '4795' => [
            'TIPO_PROPONENTE' => 'field_1294',
            'TIPO_INSTRUMENTO' => '',
            'NUMERO_INSTRUMENTO' => '',
            'ANO_INSTRUMENTO' => '',
            'CPF' => 'field_1291',
            'SEXO' => 'field_1286',
            'CNPJ' => 'field_1279',
            'FLAG_CAD_ESTADUAL' => 0,            
            'FLAG_CAD_MUNICIPAL' => 1,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,           
            'FLAG_ATUACAO_ARTES_CENICAS' => 0,
            'FLAG_ATUACAO_AUDIOVISUAL' => 0,
            'FLAG_ATUACAO_MUSICA' => 0,
            'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
            'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
            'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
            'FLAG_ATUACAO_HUMANIDADES' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica - MEI',
            'COLETIVO' => 'Coletivo', 
        ],
        'depara_sexo' => [
            'Mulher cis' => 2,
            'Homem cis' => 1,
            'Transgênero' => 1
        ]
        
        
    ]    
];